version: '3.9'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_SOURCE=http://localhost:8000
    command: ["npm", "start"]
